dist: xenial
# addons:
#   snaps:
#     - name: hugo
#       channel: extended/stable
before_install:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

script: hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: public
  repo: canovie/canovie.github.io
  target_branch: master
  committer_from_gh: true
  on:
    branch: master