dist: xenial
addons:
  snaps:
    - hugo
script: hugo
deploy: &pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public
  repo: canovie/canovie.github.io
  target_branch: master
  committer_from_gh: true
  verbose: true
  on:
    branch: master