dist: xenial
addons:
  snaps:
    - hugo
jobs:
  include:
  - stage: build
    name: Build Static Website
    script: hugo
  - stage: deploy
    name: Deploy to Github Page
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep_history: true
      local_dir: public
      repo: canovie/canovie.github.io
      target_branch: master
      committer_from_gh: true
      on:
        branch: master